config/routes.rb
AdaptiveLearning::Application.routes.draw do
  root 'static_pages#home'
  get 'definition' => 'static_pages#definition'
  get 'quiz' => 'static_pages#quiz'
  get 'product' => 'static_pages#product'
  get 'about' => 'static_pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def definition
  end

  def quiz
  end

  def product
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title_helper
    if controller.action_name
      prefix = "#{controller.action_name.capitalize} | "
    end
    "#{prefix}Adaptive Learning | EdSurge"
  end

  def load_stylesheets(opts={})
    stylesheet_link_tag "application.css"
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.slim
.navbar
  .navbar--container.pure-hidden-non-desktop
    = link_to "https://www.edsurge.com/" do
      = image_tag "EdSurgeLogo.png", alt: "EdSurge", class:"navbar--logo"
    .navbar--links
      = link_to "HOME", root_path, class:"navbar--item"
      = link_to "DEFINITION", definition_path, class:"navbar--item"
      = link_to "QUIZ", quiz_path, class:"navbar--item"
      = link_to "PRODUCT HIGHLIGHT", product_path, class:"navbar--item"
      = link_to "ABOUT", about_path, class:"navbar--item"

  .navbar--container.pure-hidden-desktop
    = link_to "https://www.edsurge.com/" do
      = image_tag "EdSurgeLogo.png", alt: "EdSurge", class:"navbar--logo"
    .navbar--links
      i.fa.fa-bars.fa-lg.navbar--item.navbar--menu-icon

.navbar--placeholder

app/views/layouts/_sharebar.html.slim
- twitter_share_link = ""
- facebook_share_link = ""
- pinterest_share_link = ""
- gplus_share_link = ""
- email_share_link = ""


- twitter_icon = capture do
  = link_to twitter_share_link, class: "social__link" do
    i.fa.fa-lg.text--twitter> class="fa-twitter-square"

- facebook_icon = capture do
  = link_to facebook_share_link, class: "social__link" do
    i.fa.fa-lg.text--facebook> class="fa-facebook-square"

- pinterest_icon = capture do
  = link_to pinterest_share_link, class: "social__link" do
    i.fa.fa-lg.text--pinterest> class="fa-pinterest-square"

- gplus_icon = capture do
  = link_to gplus_share_link, class: "social__link" do
    i.fa.fa-lg.text--gplus> class="fa-google-plus-square"

- email_icon = capture do
  = link_to email_share_link, class: "social__link" do
    i.fa.fa-lg.text--email> class="fa-envelope-square"


.textblock--aside
  = content_tag :div, class: "pure-hidden-phone"
    ul.social__vertical-stack.text--center
      li
        = twitter_icon
      li
        = facebook_icon
      li
        = pinterest_icon
      li
        = gplus_icon
      li
        = email_icon

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title_helper %></title>
  <%= stylesheet_link_tag "//fonts.googleapis.com/css?family=Source+Sans+Pro:400italic,200,400,700' rel='stylesheet" unless Rails.env.test? %>
  <%= stylesheet_link_tag "//fonts.googleapis.com/css?family=Roboto+Slab:400,700' rel='stylesheet" unless Rails.env.test? %>
  <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" %>
  <%= favicon_link_tag %>
  <%= load_stylesheets %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar" %>

<div class="navbar--body-container">
  <%= yield %>
</div>

</body>
</html>

app/views/static_pages/about.html.slim
h1 About

p TEST

app/views/static_pages/definition.html.slim
h1 Definition

app/views/static_pages/home.html.slim
.textblock

  = image_tag "test_landscape.jpg"
  = render "layouts/sharebar"

  h1 Adaptive Learning Home


  p
    ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque libero dolor, sollicitudin a tempor nec, vulputate non enim. Nulla porttitor sed ex in fringilla. Morbi pharetra nisi quis dolor porta dignissim. Nullam finibus metus non imperdiet rhoncus. Aliquam semper nisl non venenatis sollicitudin.
    a.tweet-quote Aliquam faucibus ultrices arcu vitae rutrum.
    |  Vivamus dignissim sem eu quam commodo, in vehicula magna tristique. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam cursus quam risus, id interdum risus lobortis in.

  .js-audio-player.audio--player
    .js-audio-player-mp3 src="#{asset_path('pcn.mp3')}"
    .text--center
      | Someone's name
    = image_tag "play-button.png", class:"js-audio-player-play-button audio--buttons audio--buttons-block"
    = image_tag "pause-button.png", class:"js-audio-player-pause-button audio--buttons hidden"

  p
    ' Aliquam lobortis velit vitae ex volutpat venenatis. Etiam in mollis ante, in semper nulla. Nunc vel congue mi. Phasellus pretium posuere diam, sed aliquet metus placerat sed.
    a.tweet-quote Etiam gravida quis eros eget condimentum. Aenean egestas lorem sapien, nec vehicula nisi gravida at.
    |  Sed turpis dolor, semper pretium tortor vitae, congue vulputate mi.


  h2 H2 Headline

  p.textblock--blockquote.textblock--aside
    = image_tag "SingleOpenQuote.png", class:"textblock--big-quote-image"
    | Fusce faucibus ipsum sed ante volutpat placerat.
    = image_tag "SingleClosedQuote.png", class:"textblock--big-quote-image"

  p
    | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt in justo vitae fringilla. Fusce faucibus ipsum sed ante volutpat placerat. Duis sit amet velit vel nulla gravida lobortis. Vivamus ex quam, varius vitae turpis vitae, volutpat gravida nibh. In hac habitasse platea dictumst. Curabitur fermentum urna non diam aliquam, sit amet molestie enim imperdiet. In nec ipsum ornare, feugiat nisi eu, suscipit ligula. Maecenas at ultrices sapien. Aliquam auctor diam lacus, at blandit sem ornare non. Praesent pretium condimentum dolor eu dignissim.

  h3 H3 Headline

  p
    | Vivamus sollicitudin erat in facilisis efficitur. Aenean hendrerit luctus mauris in sagittis. Etiam consequat leo vel tempus posuere. Suspendisse potenti. Nullam sit amet est placerat, gravida turpis eget, porttitor enim. Ut condimentum lobortis sapien a finibus. Aenean tincidunt lacinia leo malesuada dictum. Nunc congue justo et sapien vehicula vulputate. Quisque porttitor erat magna, et iaculis libero rhoncus vel. Donec bibendum consectetur felis quis dignissim. In in lacinia diam, quis molestie tellus. Etiam semper, enim vitae varius dignissim, risus arcu sollicitudin mi, quis accumsan neque metus quis dolor. Quisque id porta risus. Proin id libero et metus varius euismod. Suspendisse a varius augue, a tincidunt nulla. Quisque interdum diam ut vehicula fermentum.

  p.textblock--blockquote
    = image_tag "DoubleOpenQuote.png", class:"textblock--big-quote-image"
    | Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
    = image_tag "DoubleClosedQuote.png", class:"textblock--big-quote-image"

  p
    | Fusce eu leo varius, faucibus metus non, hendrerit justo. Nunc eget metus id nisl vehicula viverra id ut felis. Praesent at gravida quam. Nulla facilisi. Pellentesque aliquam lacus eu lacus euismod vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean risus urna, efficitur et pharetra quis, ornare id ante. Proin tristique justo ut interdum imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

  div.textblock--grey-background
    h4 H4 Headline
    p
      | In consequat lectus in velit cursus gravida. Vestibulum gravida arcu nec nibh malesuada gravida. Maecenas auctor porttitor neque. Aliquam lacinia turpis ac sem consequat ultricies. Duis dapibus nibh non nisi vulputate ultrices. Praesent vestibulum ante nisi, non bibendum arcu rhoncus at. Nulla lacinia molestie dolor ut lacinia. Phasellus fringilla dui dignissim ligula viverra porta. Pellentesque id volutpat enim. Curabitur id pellentesque nibh. Donec sit amet commodo urna, vitae cursus mi.

  p
    | In gravida dolor eros, sit amet cursus sem condimentum vitae. Donec vestibulum risus ut interdum posuere. Phasellus pulvinar nunc sit amet massa vulputate sagittis. Phasellus bibendum mattis facilisis. Donec dolor nisl, lobortis eu ornare eget, elementum sit amet risus. Integer nec vestibulum nisi, ut tincidunt arcu. Aliquam id tempor elit, in gravida leo. Mauris id maximus tortor. Phasellus id mi a arcu ullamcorper consequat mollis sed velit. Mauris leo augue, elementum quis iaculis eget, laoreet semper libero. Nunc non tincidunt turpis. Integer congue ullamcorper tortor a semper.

  .carousel
    br
    h3 Carousel
    .carousel-body data-carousel-items=5
      span.carousel-item
        | Item 1
      span.carousel-item
        | Item 2
      span.carousel-item
        | Item 3
      span.carousel-item
        | Item 4
      span.carousel-item
        | Item 5
    .row
      .col-md-6.carousel-button
        .fa.fa-lg.fa-arrow-circle-left.carousel-button-left
      .col-md-6.carousel-button
        .fa.fa-lg.fa-arrow-circle-right.carousel-button-right

  p
    | Nulla vel nulla tincidunt, gravida purus a, euismod dui. Aliquam faucibus dolor sit amet quam pulvinar, nec facilisis lacus congue. Duis tempus elit ante, eget suscipit purus accumsan vel. Nam ut magna tincidunt sem auctor posuere vel nec leo. Nulla quis porttitor odio. Suspendisse vitae orci tempor, gravida velit ut, bibendum metus. Quisque sagittis, risus ac tristique auctor, lectus tellus hendrerit ligula, eget tempor justo lectus at leo. Nam ex dolor, hendrerit quis leo at, sagittis sodales dolor. Integer elementum posuere consequat. Donec dapibus at diam id tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tempor risus vitae enim tristique cursus.

  p
    | Proin eget purus sit amet odio tincidunt hendrerit a vestibulum dui. Phasellus id nisi scelerisque, mattis quam quis, sollicitudin justo. Nunc tincidunt arcu tempor dolor posuere, vel fringilla felis interdum. Integer tortor ipsum, sodales sed volutpat non, ornare sit amet dolor. Morbi gravida, sem a posuere interdum, metus purus lobortis erat, vitae mattis mi dui eget sapien. Ut dictum cursus tincidunt. Sed dolor eros, lacinia et quam a, scelerisque auctor turpis. Sed ac velit tempor, placerat sapien quis, molestie velit. Duis non egestas odio, quis sollicitudin massa. Nulla venenatis nulla felis, id semper mi mattis sed. Nullam nec porttitor odio, a tincidunt diam.

  p
    | In quis lorem vestibulum, gravida lacus vitae, iaculis tortor. Donec rhoncus ipsum eget ligula porttitor, in faucibus nisl facilisis. Proin dapibus leo leo, eu condimentum felis rhoncus nec. Aenean dictum et enim a luctus. In euismod nulla sit amet mi pharetra aliquet vel ac tellus. Mauris placerat diam eget ex sagittis vestibulum. Praesent fringilla sapien mauris, ac pulvinar mauris suscipit vel.

app/views/static_pages/product.html.slim
h1 Product

app/views/static_pages/quiz.html.slim
h1 Quiz